Layout/EmptyLines:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true
  NumberOfEmptyLines: [1, 2]

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  CountKeywordArgs: false

Naming/UncommunicativeMethodParamName:
  AllowedNames: ['x', 'y', 'z', 'id']

Style/AccessModifierDeclarations:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.7
