Layout/IndentHeredoc:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true
  NumberOfEmptyLines: [1, 2]

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Max: 10

Naming/UncommunicativeMethodParamName:
  AllowedNames: ['x', 'y', 'z', 'id']

Style/AccessModifierDeclarations:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.7
